# Generated by Django 5.0.4 on 2024-04-21 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0003_remove_opendata_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='opendata',
            old_name='data',
            new_name='date',
        ),
    ]
