# Generated by Django 5.0.4 on 2024-04-21 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0005_opendate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OpenData',
        ),
    ]
